
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
        - name: tag and push
          uses: docker/build-push-action@v2
          with:
 ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

 #    - name: Kubectl Action
  #     uses: tale/kubectl-action@v1
   #    with:
    #      base64-kube-config: ${{ secrets.KUBE_CONFIG_DATA }}
     #- run: kubectl get pods        
#       -             
 #        name: deploy to cluster
  #       uses: kodermax/kubectl-aws-eks@master
   #      env:
    #      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
     #    with:
      #    args: set image deployment/whale-dep simplewhale=lwsobik/simplewhale:${{ env.GHA_SHA }} 

#           - name: verify deployment
 #            uses: kodermax/kubectl-aws-eks@master
  #           env:
   #            KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
    #        with:
     #          args: rollout status deployment/whale-dep
