
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest
          
      - uses: lacework/lw-scanner-action@v0.6.0
        name: Scan container images for vulnerabitilies using Lacework
        with:
                LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }} 
                LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
                IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale
                IMAGE_TAG: latest
                SAVE_RESULTS_IN_LACEWORK: true
                SAVE_BUILD_REPORT: true
                BUILD_REPORT_FILE_NAME: myreport.html
                FAIL_BUILD: true
                SEVERITY_THRESHOLD: fixable

