# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      -
        name: Checkout 
        uses: actions/checkout@v2
        
      -
        name: Get short SHA
        run: echo "GHA_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - 
        name: Build
        uses: docker/build-push-action@v2
        with:
          tags: lwsobik/simplewhale:${{ env.GHA_SHA }},lwsobik/simplewhale:latest
          load: true
          
      
    #  -
    #    name: Set up Docker Buildx
    #    uses: docker/setup-buildx-action@v1
   #   -
    #    name: Build and push
    #    uses: docker/build-push-action@v2
    #    with:
    #      context: .
   #       file: ./Dockerfile
    #      push: true
   #       tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest
          
      - 
        uses: lacework/lw-scanner-action@v0.6.0
        name: Scan container images for vulnerabitilies using Lacework
        with:
                LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }} 
                LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
                IMAGE_NAME: lwsobik/simplewhale
                IMAGE_TAG: ${{ env.GHA_SHA }}
                SAVE_RESULTS_IN_LACEWORK: true
                SAVE_BUILD_REPORT: true
                BUILD_REPORT_FILE_NAME: myreport.html
                FAIL_BUILD: false
                SEVERITY_THRESHOLD: fixable
      -      
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - 
        name: tag and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lwsobik/simplewhale:${{ env.GHA_SHA }},lwsobik/simplewhale:latest
          
      - 
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      -             
        name: deploy to cluster
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: set image deployment/whale-deployment simplewhale=lwsobik/simplewhale:${{ env.GHA_SHA }} -n whale 

      - 
        name: verify deployment
        uses: kodermax/kubectl-aws-eks@master
        env:
         KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: rollout status deployment/whale-deployment -w -n whale
