
                IMAGE_TAG: ${{ env.GHA_SHA }}
                SAVE_RESULTS_IN_LACEWORK: true
                SAVE_BUILD_REPORT: true
                BUILD_REPORT_FILE_NAME: myreport.html
                FAIL_BUILD: true
                SEVERITY_THRESHOLD: fixable
  
      - name: Login to Docker Hub
        uses: docker/login-action@v1
